name: Library_Management_System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: cfg@1234
          MYSQL_DATABASE: library
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/library
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: cfg@1234

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: library-management-system
          path: build/libs/*.jar