name: Library_Management_System

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: cfg@1234
          MYSQL_DATABASE: library
          MYSQL_USER: root
          MYSQL_PASSWORD: cfg@1234
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=cfg@1234" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

#    - name: Setup Gradle
#      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/library
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: cfg@1234

